// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzkrhnhzsajvbwildyvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6a3Jobmh6c2FqdmJ3aWxkeXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODY5NDMsImV4cCI6MjA1OTc2Mjk0M30.uO_1AV6ON7yyxwPkqE9FnC09OShDTMAhiKZI2lSD9E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);